#!/usr/bin/env node
/**
 * build-type.mjs — install the typographic system into the page
 *
 * Adds the font link and one override block at the very end of <head>, so it
 * wins the cascade without a single `!important` and without editing any of the
 * original rules. Remove the block and the page is exactly as it was — that is
 * the point of doing it as a layer rather than a rewrite.
 *
 * It changes letterforms and spacing only. Colour, motion, the glitch and the
 * glow are untouched.
 *
 * Usage:
 *   node scripts/build-type.mjs           install / refresh the layer
 *   node scripts/build-type.mjs --check   report, write nothing
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FONTS_HREF, DISPLAY, MONO, TITLE, VERSE, TRACK } from './lib/type.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const HTML = join(ROOT, 'index.html');
const CHECK = process.argv.includes('--check');

const START = '<!-- TYPE:START -->';
const END = '<!-- TYPE:END -->';

const block = `${START}
    <!-- Generated by scripts/build-type.mjs — do not hand-edit. -->
    <link href="${FONTS_HREF}" rel="stylesheet">
    <style id="type-css">
        /* ── The typographic layer ───────────────────────────────────────────
           An override layer, not a rewrite: every original rule is still in the
           document above this. Colour, motion, the glitch and the glow are
           deliberately untouched — this changes letterforms and spacing only. */
        :root{
            --font-display:${DISPLAY};
            --font-mono:${MONO};
            --font-title:${TITLE};
            --font-verse:${VERSE};
        }
        body{-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}

        /* Display: negative tracking is the whole move. Large type used to
           breathe; now it bites. */
        .hero-glitch{font-family:var(--font-display);font-weight:800;letter-spacing:${TRACK.hero};}
        .site-title .russian{font-family:var(--font-display);font-weight:800;letter-spacing:-.04em;}
        .section-title{font-family:var(--font-display);font-weight:800;letter-spacing:${TRACK.display};}
        /* Poem titles use the CYRILLIC-CAPABLE face, not the display face. Syne
           has no Cyrillic, so 43 Russian titles were falling back to Inter while
           the English ones set in Syne — half the vault looking unstyled. */
        .nft-title{font-family:var(--font-title);font-weight:600;letter-spacing:${TRACK.title};}

        /* ── The poems themselves ────────────────────────────────────────────
           Inter italic is an oblique of a UI typeface: soft, and the same shapes
           as every dashboard. Geist Mono is sharper, current, and honest about
           what this is — poetry committed to a chain by someone who codes. Set
           upright, because mono italic is a slant rather than a design. Full
           Cyrillic, so the Russian half sets exactly like the English half.
           The red rule, the colour and the spacing around it are untouched. */
        .nft-verse{font-family:var(--font-verse);font-style:normal;font-weight:400;
            font-size:.95rem;line-height:1.78;letter-spacing:-.005em;}
        @media (max-width:760px){ .nft-verse{font-size:.88rem;line-height:1.72;} }
        /* .poem-title is deliberately NOT here — it is bilingual and belongs to
           --font-title. Listing it under the display face would contradict the
           vault's own sheet and confuse whoever reads this next. */
        .vault-title,.part-title,.dna-pull q,.dna-n{
            font-family:var(--font-display);letter-spacing:${TRACK.title};}
        .poem-title{font-family:var(--font-title);letter-spacing:${TRACK.title};}
        .vault-title{font-weight:700;letter-spacing:${TRACK.display};}
        .part-title{font-weight:800;}
        .dna-n{font-weight:700;letter-spacing:-.04em;}

        /* Technical: the counterpoint — tiny, wide, even. */
        .site-title .english{font-family:var(--font-mono);letter-spacing:${TRACK.logo};font-size:.6rem;font-weight:300;}
        .hero-subtitle{font-family:var(--font-mono);letter-spacing:${TRACK.labelWide};font-size:.8rem;font-weight:400;}
        .nav-link{font-family:var(--font-mono);font-size:.7rem;letter-spacing:${TRACK.label};
            text-transform:uppercase;font-weight:400;}
        .nft-id,.nft-status,.nft-price,.blockchain-badge,
        .poem-num,.poem-date,.poem-lang,.poem-status,.poem-open,.poem-permalink,
        .part-num,.part-note,.part-count,.run-y,.run-n,
        .vault-kicker,.vault-tally,.vault-find,.dna-l,.dna-sign{
            font-family:var(--font-mono);}

        /* Numbers in true columns. #045, the dates and the tallies stop
           shimmering by a pixel from row to row. */
        .poem-num,.poem-date,.part-count,.run-y,.run-n,.vault-tally,
        .nft-id,.dna-n,.slot-id,.slot-year{font-variant-numeric:tabular-nums;font-feature-settings:"tnum" 1;}

        /* Hairlines. A 1px solid grey rule reads as a border; a hairline at low
           alpha reads as a fold in the paper. */
        .poem{border-bottom-color:rgba(168,168,168,.09);}
        .part{border-bottom-color:rgba(168,168,168,.16);}
        .run-rule{background:rgba(168,168,168,.13);}
        .poem-leader{background:rgba(168,168,168,.2);}

        @media (max-width:760px){
            .hero-glitch{letter-spacing:-.035em;}
            .site-title .english{letter-spacing:.2em;}
        }
    </style>
    ${END}`;

let html = readFileSync(HTML, 'utf8');
let action;

if (html.includes(START) && html.includes(END)) {
  const a = html.indexOf(START);
  const b = html.indexOf(END) + END.length;
  html = html.slice(0, a) + block + html.slice(b);
  action = 'refreshed';
} else {
  const head = html.lastIndexOf('</head>');
  if (head < 0) throw new Error('no </head> — refusing to guess where the type layer goes');
  html = html.slice(0, head) + block + '\n' + html.slice(head);
  action = 'installed';
}

/* The layer must not disturb anything structural. */
const counts = (s) => ({
  cards: (s.match(/<div class="nft-card">/g) || []).length,
  buttons: (s.match(/<button class="nft-action"/g) || []).length,
  slots: (s.match(/class="gallery-slot"/g) || []).length,
  poems: (s.match(/class="poem" id="p/g) || []).length,
});
const before = counts(readFileSync(HTML, 'utf8'));
const after = counts(html);
for (const k of Object.keys(before)) {
  if (before[k] !== after[k]) throw new Error(`${k} changed ${before[k]} → ${after[k]} — refusing to write`);
}
if ((html.match(new RegExp(START, 'g')) || []).length !== 1) throw new Error('type layer duplicated');

if (CHECK) {
  console.log(`build-type --check: would be ${action}. Nothing written.`);
} else {
  writeFileSync(HTML, html, 'utf8');
  console.log(`build-type: type layer ${action} — Syne display, Geist Mono technical, tabular numerals.`);
  console.log(`  ${after.poems} poem rows, ${after.cards} cards, ${after.buttons} claim buttons untouched.`);
}
