#!/usr/bin/env node
/**
 * build-dna.mjs — the DNA section, and the nav that reaches it
 *
 * The site already held this material, in the right voice, in the wrong place:
 * a modal opened by clicking the words "Underground Aesthetic" under the logo.
 * Nothing in the navigation pointed at it, so the one page that says who made
 * the ninety-nine was the one page nobody could find. Meanwhile the section
 * labelled MANIFEST carried house boilerplate — "rebellion against the sterile",
 * "POWERED BY POLYGON" — with no author anywhere in it.
 *
 * So DNA becomes its own destination, the way it is on the galleries that do this
 * properly, and it is written in the FIRST PERSON. The modal's copy speaks about
 * Kira in the third person — "her fingers danced across keys" — which is a press
 * release, not a DNA. Where a line of hers already existed in her own voice it is
 * kept verbatim; nothing about her life is invented here.
 *
 * Every number below is counted from content/poems.json at build time, so this
 * page cannot drift from the vault the way index.html drifted from its poems.
 *
 * Nav order, as asked: VAULT · DNA · MANIFEST · FILM STUDIO · MINT
 *
 * Usage: node scripts/build-dna.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const HTML = join(ROOT, 'index.html');
const DATA = join(ROOT, 'content', 'poems.json');

const poems = JSON.parse(readFileSync(DATA, 'utf8'));

/* Counted, never asserted. */
const total = poems.length;
const litprom = poems.filter((p) => p.venue === 'LITPROM');
const atuona = poems.filter((p) => p.venue === 'ATUONA');
const yearsOf = (set) => {
  const ys = set.map((p) => Number(p.year)).filter(Boolean);
  return { from: Math.min(...ys), to: Math.max(...ys) };
};
const lp = yearsOf(litprom);
const at = yearsOf(atuona);

const NAV_START = '<!-- NAV:START -->';
const NAV_END = '<!-- NAV:END -->';
const DNA_START = '<!-- DNA:START -->';
const DNA_END = '<!-- DNA:END -->';

const nav = `${NAV_START}
                <a href="#home" class="nav-link active space" data-text="VAULT">VAULT</a>
                <a href="#dna" class="nav-link space" data-text="DNA">DNA</a>
                <a href="#about" class="nav-link space" data-text="MANIFEST">MANIFEST</a>
                <a href="/aifilmstudio/" class="nav-link space" data-text="FILM STUDIO">FILM STUDIO</a>
                <a href="#gallery" class="nav-link space" data-text="MINT">MINT</a>
                ${NAV_END}`;

const CSS = `
    /* ── DNA ─────────────────────────────────────────────────────────────
       Generated by scripts/build-dna.mjs. Do not hand-edit. */
    .dna-content{max-width:760px;margin:0 auto;padding:1rem 1rem 5rem;}
    .dna-pull{border-left:2px solid var(--red-dark);padding:.4rem 0 .4rem 1.6rem;margin:0 0 3rem;}
    .dna-pull q{font-family:'Space Grotesk','Inter',sans-serif;font-size:clamp(1.3rem,3.2vw,1.9rem);
      font-weight:300;font-style:italic;color:var(--silver-bright);line-height:1.35;quotes:none;}
    .dna-body p{color:var(--silver-medium);font-size:1.02rem;line-height:1.85;margin:0 0 1.6rem;}
    .dna-body p.lede{font-size:1.18rem;color:var(--silver-bright);}
    .dna-body .highlight{color:var(--red-crimson);}
    .dna-body a{color:var(--red-crimson);text-decoration:none;border-bottom:1px solid var(--red-dark);
      transition:color .25s,border-color .25s;}
    .dna-body a:hover{color:var(--silver-bright);border-color:var(--silver-grey);}

    /* The counted spine — the only numbers on this page, read from the vault. */
    .dna-ledger{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:1px;
      background:var(--grey-dark);border:1px solid var(--grey-dark);margin:2.6rem 0 3rem;}
    .dna-cell{background:var(--deep-black);padding:1.3rem 1.2rem;}
    .dna-n{font-family:'Space Grotesk','Inter',sans-serif;font-size:1.9rem;font-weight:300;
      color:var(--red-crimson);line-height:1;margin-bottom:.55rem;}
    .dna-l{font-family:'JetBrains Mono',monospace;font-size:.62rem;letter-spacing:.16em;
      text-transform:uppercase;color:var(--silver-dark);line-height:1.5;}

    .dna-said{border-left:2px solid var(--grey-medium);padding-left:1.4rem;margin:0 0 1.6rem;}
    .dna-said p{color:var(--silver-dark);font-style:italic;margin-bottom:.5rem;}

    .dna-sign{font-family:'JetBrains Mono',monospace;font-size:.72rem;letter-spacing:.22em;
      text-transform:uppercase;color:var(--red-dark);margin-top:3.4rem;padding-top:1.8rem;
      border-top:1px solid var(--grey-dark);}
`;

const section = `${DNA_START}
            <style id="dna-css">${CSS}            </style>
            <section id="dna" class="section hidden">
                <div class="dna-content">
                    <h2 class="section-title">DNA</h2>

                    <div class="dna-pull">
                        <q>You cannot choose your revelations.</q>
                    </div>

                    <div class="dna-body">
                        <p class="lede">
                            I am <span class="highlight">Kira Velerevich</span>. I write the poems, and I build
                            the gallery they live in. Both halves are mine, and neither one
                            explains the other away.
                        </p>

                        <p>
                            Atuona is the village in the Marquesas where Gauguin is buried — the far
                            edge a painter went to when there was nowhere further to go. I took the name
                            for a poem first. The gallery came after, and kept it.
                        </p>

                        <div class="dna-ledger">
                            <div class="dna-cell">
                                <div class="dna-n">${total}</div>
                                <div class="dna-l">Moments<br>in the vault</div>
                            </div>
                            <div class="dna-cell">
                                <div class="dna-n">${litprom.length}</div>
                                <div class="dna-l">Published by LITPROM<br>${lp.from}–${lp.to}</div>
                            </div>
                            <div class="dna-cell">
                                <div class="dna-n">${atuona.length}</div>
                                <div class="dna-l">Self-published here<br>${at.from}–${at.to}</div>
                            </div>
                            <div class="dna-cell">
                                <div class="dna-n">2</div>
                                <div class="dna-l">Languages<br>Russian and English</div>
                            </div>
                        </div>

                        <p>
                            Roughly half of them are in Russian and half in English. I do not translate
                            myself for anyone's comfort — the moment picks its language and I follow it.
                        </p>

                        <p>
                            <span class="highlight">Nothing here is for sale.</span> Claiming a moment costs
                            gas and nothing else, and the chain hands you one you did not pick. That is
                            deliberate. In a world where the algorithm predicts what you want and feeds it
                            back to you, this gallery refuses: you arrive thinking you know which pain is
                            yours, and the moment chooses you instead.
                        </p>

                        <p>
                            To the editorial collective that made half of this vault exist before any of
                            it was on a chain:
                        </p>
                        <div class="dna-said">
                            <p>I love you, LITPROM — for publishing the unpublishable, for making these
                            soul fragments live when the world wanted them buried.</p>
                        </div>

                        <p>
                            I write from Panama. I built this gallery, the
                            <a href="/aifilmstudio/">film studio</a> inside it, and the agent that publishes
                            to it — so the poems keep arriving whether or not I am at a desk that day.
                        </p>
                        <div class="dna-said">
                            <p>Some revolutionaries fight with guns. Others fight with code. I chose the
                            latter, and the blockchain will remember.</p>
                        </div>

                        <p>
                            The engineering half of me lives at
                            <a href="https://aideazz.xyz/portfolio" target="_blank" rel="noopener">aideazz.xyz/portfolio</a>
                            — the systems, the outages, and what each one taught me.
                        </p>

                        <div class="dna-sign">— From Atuona, with love</div>
                    </div>
                </div>
            </section>
            ${DNA_END}`;

let html = readFileSync(HTML, 'utf8');

/* ── Nav ─────────────────────────────────────────────────────────────────── */
if (html.includes(NAV_START) && html.includes(NAV_END)) {
  const a = html.indexOf(NAV_START);
  const b = html.indexOf(NAV_END) + NAV_END.length;
  html = html.slice(0, a) + nav + html.slice(b);
} else {
  // First run: swallow the four existing links, leave the wallet button alone.
  const first = html.indexOf('<a href="#home" class="nav-link');
  const wallet = html.indexOf('<button class="nav-link space wallet-status"');
  if (first < 0 || wallet < 0 || wallet < first) {
    throw new Error('cannot locate the nav links ahead of the wallet button — refusing to guess');
  }
  html = html.slice(0, first) + nav + '\n                ' + html.slice(wallet);
}

/* ── Section ─────────────────────────────────────────────────────────────── */
if (html.includes(DNA_START) && html.includes(DNA_END)) {
  const a = html.indexOf(DNA_START);
  const b = html.indexOf(DNA_END) + DNA_END.length;
  html = html.slice(0, a) + section + html.slice(b);
} else {
  const about = html.indexOf('<section id="about"');
  if (about < 0) throw new Error('cannot find #about — refusing to guess where DNA goes');
  html = html.slice(0, about) + section + '\n\n            ' + html.slice(about);
}

/* ── Gates ───────────────────────────────────────────────────────────────── */
const order = ['VAULT', 'DNA', 'MANIFEST', 'FILM STUDIO', 'MINT'];
const got = [...html.matchAll(/<a href="[^"]*" class="nav-link[^"]*"[^>]*>([^<]+)<\/a>/g)].map((m) => m[1].trim());
if (JSON.stringify(got) !== JSON.stringify(order)) {
  throw new Error(`nav order wrong: got ${JSON.stringify(got)}, want ${JSON.stringify(order)}`);
}
for (const need of ['id="manifestoModal"', 'showManifesto()', 'id="about"', 'id="gallery"', 'id="root"',
                    'wallet-status', 'VAULT:TREE:START']) {
  if (!html.includes(need)) throw new Error(`DNA build would drop ${need} — refusing to write`);
}
if ((html.match(/<section id="dna"/g) || []).length !== 1) throw new Error('DNA section duplicated');

writeFileSync(HTML, html, 'utf8');
console.log('build-dna: #dna section + nav → index.html');
console.log('  nav order:', got.join(' · '));
console.log(`  ledger: ${total} moments · LITPROM ${litprom.length} (${lp.from}–${lp.to}) · ATUONA ${atuona.length} (${at.from}–${at.to})`);
